package:
  name: bash
  version: 5.2.32
  epoch: 2
  description: "GNU bourne again shell"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/bash/bash-${{package.version}}.tar.gz
      expected-sha256: d3ef80d2b67d8cbbe4d3265c63a72c46f9b278ead6e0e06d61801b58f23f50b5

  - runs: |
      ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --bindir=/bin \
        --sysconfdir=/etc \
        --without-libidn \
        --with-ssl=openssl \
        --disable-nls \
        --enable-readline \
        --without-bash-malloc \
        --with-curses

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: bash-binsh
    dependencies:
      provider-priority: 60
      runtime:
        - bash
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -s bash "${{targets.subpkgdir}}"/bin/sh
    test:
      pipeline:
        - runs: |
            [ /bin/sh -ef /bin/bash ] || { echo "/bin/sh is not same as /bin/bash"; exit 1; }

  - name: "bash-doc"
    description: "bash documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/

  - name: "bash-dev"
    description: "bash development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          mv "${{targets.destdir}}"/bin/bashbug "${{targets.subpkgdir}}"/bin/

  - name: "bash-builtins"
    description: "bash loadable builtins"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv "${{targets.destdir}}/usr/lib/bash" ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 166

test:
  pipeline:
    - runs: |
        out=$(/bin/bash --version)
        echo "$out" | grep "${{package.version}}"
    - runs: |
        out=$(/bin/bash -c "echo hello world")
        [ "$out" = "hello world" ]
