package:
  name: cilium-operator-aws
  version: 1.16.0
  epoch: 2
  description: eBPF-based Networking, Security, and Observability
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - gops

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium
      tag: v${{package.version}}
      expected-commit: 82999990bc954699cf24853ef9747d9166ee24c8

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - runs: |
      cd /home/build/operator
      make cilium-operator-aws
      DESTDIR=${{targets.destdir}} make install-aws

  - uses: strip

test:
  pipeline:
    - runs: cilium-operator-aws --version

update:
  enabled: true
  github:
    identifier: cilium/cilium
    strip-prefix: v
