package:
  name: crun
  version: 1.16.1
  epoch: 0
  description: "Fast and lightweight fully featured OCI runtime and C library for running containers"
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go-md2man
      - libcap-dev
      - libseccomp
      - libseccomp-dev
      - python3
      - wolfi-base
      - yajl
      - yajl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/containers/crun/releases/download/${{package.version}}/crun-${{package.version}}.tar.gz
      expected-sha512: 5e22d74660e2c36726292c4160b1461782b27805a33ade769854ed42d8fd4027f5f88e646d393337aa785566cd8be3d0e5175da8e146f18232eb772b6034ea69

  - runs: |
      ./configure \
         --prefix=/usr \
         --disable-systemd

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: crun-doc
    pipeline:
      - uses: split/manpages
    description: crun manpages

update:
  enabled: true
  release-monitor:
    identifier: 96792
