package:
  name: druid
  version: 30.0.0
  epoch: 0
  description: Apache Druid is a high performance real-time analytics database.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - busybox
      - openjdk-17-default-jvm

environment:
  contents:
    packages:
      - bash
      - busybox
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - py3-pyyaml
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/druid.git
      tag: druid-${{package.version}}
      expected-commit: 09d36ee324747f1407705c27618b6d415c3fa8a9
      cherry-picks: |
        master/75937c98e82156d8812143a047baf3f2a8af6b72: CVE-2023-3635

  - runs: |
      mvn -B -ff -q \
      install \
      -Pdist,bundle-contrib-exts \
      -Pskip-static-checks,skip-tests \
      -Dmaven.javadoc.skip=true -T1C

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/java/druid
      tar -zxf distribution/target/apache-druid-${{package.version}}-bin.tar.gz --strip-components=1 -C ${{targets.destdir}}/usr/share/java/druid

  - runs: |
      # deduplicate jars
      cp distribution/docker/deduplicate_jars.sh ${{targets.destdir}}/deduplicate_jars.sh
      ${{targets.destdir}}/deduplicate_jars.sh ${{targets.destdir}}/usr/share/java/druid

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to copy the entrypoint scripts"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"
          cp distribution/docker/druid.sh ${{targets.subpkgdir}}/druid.sh
          cp distribution/docker/peon.sh ${{targets.subpkgdir}}/peon.sh

          sed -i "s|/opt/druid|/usr/share/java/druid|" ${{targets.subpkgdir}}/druid.sh
          sed -i "s|/opt/druid|/usr/share/java/druid|" ${{targets.subpkgdir}}/peon.sh
    dependencies:
      runtime:
        - iproute2

test:
  environment:
    contents:
      packages:
        - python3
        - perl
  pipeline:
    - runs: |
        /usr/share/java/druid/bin/start-nano-quickstart > /usr/share/java/druid/logs.txt 2>&1 &
        DRUID_PID=$!
        sleep 2
        grep -q "Starting Apache Druid" /usr/share/java/druid/logs.txt
        kill $DRUID_PID

update:
  enabled: true
  github:
    identifier: apache/druid
    use-tag: true
    tag-filter: druid-
    strip-prefix: druid-
