package:
  name: fluent-plugin-systemd
  version: 1.0.5
  epoch: 0
  description: This is a fluentd input plugin. It reads logs from the systemd journal.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - systemd-dev

vars:
  gem: fluent-plugin-systemd

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 216547e23455d4c4ebe36ff809c81d0222d6adc9
      repository: https://github.com/fluent-plugins-nursery/fluent-plugin-systemd
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

test:
  environment:
    contents:
      packages:
        - busybox
        - systemd-dev
  pipeline:
    - runs: |
        gem install systemd-journal
        ruby -e "require 'fluent/plugin/in_systemd'"
        ruby -e "require 'fluent/plugin/filter_systemd_entry'"
        ruby -e "require 'fluent/plugin/systemd/entry_mutator'"

update:
  enabled: true
  github:
    identifier: fluent-plugins-nursery/fluent-plugin-systemd
    strip-prefix: v
    use-tag: true
