package:
  name: golangci-lint
  version: 1.60.1
  epoch: 0
  description: Fast linters Runner for Go
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - diffutils

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/golangci/golangci-lint
      tag: v${{package.version}}
      expected-commit: 3298c104802d118670a487b330ddd3761f7afe20

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin/
      cp ./golangci-lint ${{targets.destdir}}/usr/bin/golangci-lint

  - uses: strip

update:
  enabled: true
  github:
    identifier: golangci/golangci-lint
    strip-prefix: v
