package:
  name: hubble
  version: 1.16.0
  epoch: 1
  description: hubble is a command to list and diagnose Go processes currently running on your system.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/hubble
      tag: v${{package.version}}
      expected-commit: 930a8cf4d11175a34e11e6fecaca425ba9dfa330

  - uses: go/bump
    with:
      deps: github.com/cilium/cilium@v1.16.1

  - runs: |
      DESTDIR=${{targets.destdir}} BINDIR=/usr/bin make install

  - uses: strip

subpackages:
  - name: hubble-compat
    description: Compatibility package for hubble
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/hubble ${{targets.subpkgdir}}/usr/local/bin/hubble
      - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/hubble
    strip-prefix: v
