package:
  name: istio-operator-1.23
  version: 1.23.0
  epoch: 1
  description: Istio operator provides user friendly options to operate the Istio service mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-operator=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: d0ca037e58f90f58b38b33c5769fec25b6bfa9f3

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5

  - uses: go/build
    with:
      packages: ./operator/cmd/operator
      output: operator
      # Extracted from https://github.com/istio/istio/blob/4358b84b911a80ba09ef36ac00ad85535a77e7ca/common/scripts/report_build_info.sh#L41-L48
      # Use this instead for buildStatus once our pipeline stops dirtying the git tree: "$(if git diff-index --quiet HEAD --; then echo "Clean"; else echo "Modified"; fi)"
      ldflags: |
        -X istio.io/istio/pkg/version.buildVersion=${{package.version}}
        -X istio.io/istio/pkg/version.buildGitRevision=$(git rev-parse HEAD)
        -X istio.io/istio/pkg/version.buildTag=$(git describe --tags --always)
        -X istio.io/istio/pkg/version.buildStatus="Clean"

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio
      mv manifests ${{targets.destdir}}/var/lib/istio/manifests

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.23.
    use-tag: true
