package:
  name: karpenter
  version: 1.0.0
  epoch: 0
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter
      tag: v${{package.version}}
      expected-commit: 5bdf9c3a9d6b01dc6934c3807dfa69160d411131

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/karpenter
    strip-prefix: v
