package:
  name: kubewatch
  version: 2.8.0
  epoch: 0
  description: Watch k8s events and trigger Handlers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 80907c67435b1a0461ecab33d18353f5a9fc6822
      repository: https://github.com/robusta-dev/kubewatch
      tag: v${{package.version}}

  # Temporary Fix: Upstream go.sum file does not accurately capture package dependencies.
  - runs: |
      go mod tidy

  - uses: go/build
    with:
      output: kubewatch
      packages: .

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: robusta-dev/kubewatch
    strip-prefix: v
