package:
  name: libevdev
  version: 1.13.2
  epoch: 1
  description: Kernel Evdev Device Wrapper Library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - doxygen
      - linux-headers
      - python3

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3eca86a6ce55b81d5bce910637fc451c8bbe373b1f9698f375c7f1ad0de3ac48
      uri: https://www.freedesktop.org/software/libevdev/libevdev-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: -Dtests=disabled

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: libevdev-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - linux-headers
    description: libevdev dev

  - name: libevdev-doc
    pipeline:
      - uses: split/manpages
    description: libevdev manpages

  - name: libevdev-tools
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/* "${{targets.contextdir}}"/usr/bin/
    description: libevdev utilities

update:
  enabled: true
  release-monitor:
    identifier: 20540
