package:
  name: nuclei
  version: 3.3.1
  epoch: 0
  description: "yaml based vulnerability scanner"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - go
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8c0dd5fac18ccd39e014251dc1d7aef4e0c38851
      repository: https://github.com/projectdiscovery/nuclei
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/mholt/archiver/v3@v3.5.2
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2

  - uses: patch
    with:
      patches: GHSA-4v7x-pqxf-cx7m.patch

  - uses: go/build
    with:
      modroot: .
      packages: cmd/nuclei/main.go
      output: nuclei

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: projectdiscovery/nuclei
