package:
  name: opa
  version: 0.67.1
  epoch: 0
  description: Open Policy Agent (OPA) is an open source, general-purpose policy engine.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-policy-agent/opa
      tag: v${{package.version}}
      expected-commit: b88c09e9e948bd41ec6eb2b93a8d6a269f255698

  - uses: go/build
    with:
      ldflags: "-X github.com/open-policy-agent/opa/version.Version=${{package.version}}"
      modroot: .
      packages: .
      output: opa

  - uses: strip

update:
  enabled: true
  github:
    identifier: open-policy-agent/opa
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        opa version
        opa test . -v
