package:
  name: opentofu
  version: 1.8.1
  epoch: 0
  copyright:
    - license: MPL-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7cdad9e993b23f6e0d3762ca1842ba62da231f16
      repository: https://github.com/opentofu/opentofu
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/opentofu/opentofu/version.dev=no'
      modroot: .
      output: tofu
      packages: ./cmd/tofu

  - uses: strip

subpackages:
  - name: opentofu-compat
    description: Compat package for opentofu
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/opentofu "${{targets.subpkgdir}}"/usr/local/bin

  - name: opentofu-local-provider-config
    description: Configure opentofu to use local providers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opentofu/provider-mirror
          cat > "${{targets.subpkgdir}}"/opentofu/.opentofurc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/opentofu/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc'
    - 'beta'
  github:
    identifier: opentofu/opentofu
    strip-prefix: v
    use-tag: true
    tag-filter: v
