package:
  name: parseable
  version: 1.4.0
  epoch: 0
  description: "Parseable is a log analytics system built for high throughput log ingestion cases."
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/parseablehq/parseable
      tag: v${{package.version}}
      expected-commit: 713ef35ad1dc1a2ca3656fa6ded1eb053775dd36

  - runs: |
      cargo auditable build --release
      install -Dm755 target/release/parseable "${{targets.destdir}}"/usr/bin/parseable

  - uses: strip

update:
  enabled: true
  github:
    identifier: parseablehq/parseable
    strip-prefix: v
