package:
  name: py3-typing
  version: 3.10.0.0
  epoch: 3
  description: Type Hints for Python
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 13b4ad211f54ddbf93e5901a9967b1e07720c1d1b78d596ac6a439641aa1b130
      uri: https://files.pythonhosted.org/packages/source/t/typing/typing-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  manual: true # fetch URL contains a sha so will need to be manually
  shared: true
  release-monitor:
    identifier: 10922

test:
  pipeline:
    - uses: python/import
      with:
        import: typing
