package:
  name: py3-rich
  version: 13.7.1
  epoch: 0
  description: "Rich is a Python library for rich text and beautiful formatting in the terminal."
  copyright:
    - license: LGPL-2.1-or-later
  dependencies:
    runtime:
      - py3-markdown-it-py
      - py3-pygments
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Textualize/rich
      tag: v${{package.version}}
      expected-commit: 7f580bdcf07a3b269a0e786b6a3aa9c804f393cf

  - runs: |
      export SETUPTOOLS_SCM_PRETEND_VERSION=${{package.version}}
      python3 -m pip install -U poetry
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer -d "${{targets.destdir}}" \
        dist/*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: Textualize/rich
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - py3-pip
    environment:
      RICH_TEST_STRING: "This is a test string for Rich!"
  pipeline:
    - name: Test Rich Installation
      runs: |
        python3 -m pip install rich
        python3 -c "from rich import print; print('${RICH_TEST_STRING}')"
    - name: Test Rich Formatting Capabilities
      runs: |
        python3 -c "from rich.console import Console; console = Console(); console.print('${RICH_TEST_STRING}', style='bold red')"
    - name: Test Rich JSON Rendering
      runs: |
        python3 -c "from rich import print; print({'json': ['Renders', 'well', 'in', 'Rich']})"
