package:
  name: py3-portalocker
  version: 2.10.1
  epoch: 0
  description: An easy library for Python file locking. It works on Windows, Linux, BSD and Unix systems and can even perform distributed locking. Naturally it also supports the with statement
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolph/portalocker
      expected-commit: 4d5905f14015dfa1561b9f3efff9e59ed03df5ba
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: wolph/portalocker
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        import: portalocker
