package:
  name: py3-jsonschema
  version: 4.23.0
  epoch: 0
  description: "Python Classes Without Boilerplate."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-attrs
      - py3-jsonschema-specifications
      - py3-referencing
      - py3-rpds-py
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-jsonschema/jsonschema
      tag: v${{package.version}}
      expected-commit: cfe8a4071672b9652c8f083faed1c4ffa7d67705

  - runs: |
      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
      export SOURCE_DATE_EPOCH=315532800
      python3 -m pip install -U hatchling hatch-vcs hatch-fancy-pypi-readme
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/jsonschema-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-jsonschema/jsonschema
    tag-filter: v
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        import: jsonschema
