package:
  name: py3-simplejson
  version: 3.19.3
  epoch: 0
  description: Simple, fast, extensible JSON encoder/decoder for Python
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/simplejson/simplejson
      tag: v${{package.version}}
      expected-commit: 6932004966ab70ef47250a2b3152acd8c904e6b5

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import simplejson

update:
  enabled: true
  github:
    identifier: simplejson/simplejson
    strip-prefix: v
