package:
  name: py3-maturin
  version: 1.7.0
  epoch: 2
  description: Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
  copyright:
    - license: MIT OR Apache-2.0
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-python-dev
      - py3-supported-setuptools
      - py3-supported-setuptools-rust
      - py3-supported-wheel
      - rust
      - wolfi-base

vars:
  pypi-package: maturin

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2061d01bf40ee4c753cc03b84e22ac226a962414
      repository: https://github.com/pyo3/maturin
      tag: v${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-tomli
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}/usr/bin ${{targets.contextdir}}/usr
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}

update:
  enabled: true
  ignore-regex-patterns:
    - 'beta'
  github:
    identifier: pyo3/maturin
    strip-prefix: v
