package:
  name: py3-more-itertools
  version: 10.4.0
  epoch: 0
  description: "more routines for operating on iterables, beyond itertools"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/more-itertools/more-itertools.git
      tag: v${{package.version}}
      expected-commit: 935db916c76a66ba1190d1cf20d5ade341f62d14

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: more-itertools/more-itertools
    strip-prefix: v
