package:
  name: py3-pyjwt
  version: 2.9.0
  epoch: 0
  description: JSON Web Token implementation in Python
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-typing-extensions
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - py3-typing-extensions
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jpadilla/pyjwt/
      tag: ${{package.version}}
      expected-commit: 868cf4ab2ca5a0a39da40e5a14dd740b203662b2

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: jpadilla/pyjwt
