package:
  name: py3-psutil
  version: 5.9.5
  epoch: 3
  description: Cross-platform lib for process and system monitoring in Python.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provider-priority: 0
    runtime:
      - linux-headers
      - python3
      - python3-dev

vars:
  pypi-package: psutil

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - py3-supported-pip
      - py3-supported-python-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/giampaolo/psutil
      expected-commit: 0d4900b073f8697ab21c47d823621bea61f39a3b
      tag: release-${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - runs: python${{range.key}} -c "import psutil"

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: giampaolo/psutil
    strip-prefix: release-

test:
  environment:
    contents:
      packages:
        - python3
  pipeline:
    - uses: python/import
      with:
        import: psutil
