package:
  name: py3-cython
  version: 3.0.11
  epoch: 0
  description: Cython is an optimising static compiler for both the Python & the extended Cython programming languages.
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: cython

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-pip
      - py3-supported-python-dev
      - py3-supported-wheel

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2ec7d66d23d6da2328fb24f5c1bec6c63a59ec2e91027766ab904f417e1078aa
      uri: https://github.com/cython/cython/archive/${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - cython
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - name: py3-wheels-${{vars.pypi-package}}
    pipeline:
      - uses: py/collect-wheels

update:
  enabled: true
  github:
    identifier: cython/cython

test:
  pipeline:
    - uses: python/import
      with:
        import: cython
