package:
  name: py3-scipy
  version: 1.14.0
  epoch: 1
  description: Fundamental algorithms for scientific computing in Python
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - numpy
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - gfortran
      - meson
      - ninja-build
      - numpy
      - openblas-dev
      - py3-numpy
      - py3-numpy-bin
      - py3-pip
      - py3-pybind11-dev
      - py3-pythran
      - python3
      - python3-dev
      - rsync
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/scipy/scipy
      expected-commit: 87c46641a8b3b5b47b81de44c07b840468f7ebe7
      tag: v${{package.version}}

  - runs: git submodule update --init

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: scipy/scipy
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - python3
  pipeline:
    - runs: |
        python3 -c "import scipy"
