package:
  name: py3-rpds-py
  version: 0.20.0
  epoch: 0
  description: "Python bindings to Rust's persistent data structures (rpds)."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/crate-py/rpds
      tag: v${{package.version}}
      expected-commit: fac4daa73aacf2df7b4341d51f0c24f5f80aa03d

  - runs: |
      python3 -m pip install -U maturin
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/rpds_py-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: crate-py/rpds
    strip-prefix: v
