package:
  name: py3-forestci
  version: "0.7"
  epoch: 0
  description: 'forestci: confidence intervals for scikit-learn forest algorithms'
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - py3-scikit-learn
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/scikit-learn-contrib/forest-confidence-interval
      expected-commit: c5379afd17725f29afb6f93a66f895f71848ec6f
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: scikit-learn-contrib/forest-confidence-interval

test:
  pipeline:
    - uses: python/import
      with:
        import: forestci
