package:
  name: py3-google-auth
  version: 2.34.0
  epoch: 0
  description: Google Authentication Library
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-asn1-modules
      - py3-cachetools
      - py3-rsa
      - py3-six
      - py3-urllib3
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/googleapis/google-auth-library-python
      tag: v${{package.version}}
      expected-commit: c6d99030b8d972105913006bd052cf762b94a976

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: googleapis/google-auth-library-python
    strip-prefix: v
