package:
  name: py3-peewee
  version: 3.17.6
  epoch: 0
  description: "a little orm"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coleifer/peewee
      tag: ${{package.version}}
      expected-commit: 0b16576460439297874732c8cf42761371d5c6a4

  - runs: |
      NO_SQLITE=1 python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/peewee-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: coleifer/peewee

test:
  pipeline:
    - uses: python/import
      with:
        import: peewee
