# This package provides a binary wheel for python-3.XX packages
# in lieu of ensurepip's bundled wheels.  It allows us to proctively
# update those wheels by tracking the upstream package release.
# python is compiled with --with-wheel-pkg-dir=/usr/share/python-wheels
package:
  name: py3-setuptools-wheel
  version: 72.2.0
  epoch: 0
  description: "python3 setuptools wheel from pypi"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/s/setuptools/setuptools-${{package.version}}-py3-none-any.whl
      expected-sha256: f11dd94b7bae3a156a95ec151f24e4637fb4fa19c878e4d191bfb8b2d82728c4
      extract: false

  - name: Install wheel
    runs: |
      wdir="${{targets.contextdir}}/usr/share/python-wheels"
      mkdir -p "$wdir"
      cp -v *.whl "$wdir"

update:
  enabled: true
  release-monitor:
    identifier: 4021
