package:
  name: ruby3.2-oj
  version: 3.16.5
  epoch: 0
  description: The fastest JSON parser and object serializer.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: oj

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f5e928a700a391815dc88e6ed25e8f04046b0b40
      repository: https://github.com/ohler55/oj
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: ohler55/oj
    strip-prefix: v
    use-tag: true
