package:
  name: rye
  version: 0.38.0
  epoch: 0
  description: "An Experimental Package Management Solution for Python"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - openssl-dev
      - perl
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/rye
      expected-commit: 3e3c8540f7f72e5742d6e347f392b2631c0b1b4d
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      # mitigate GHSA-x4gp-pqpj-f43q
      cargo update curve25519-dalek --precise 4.1.3

      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/${{package.name}} ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: astral-sh/rye
