package:
  name: seaweedfs
  version: "3.72"
  epoch: 0
  description: SeaweedFS is a fast distributed storage system for blobs, objects, files.
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"
    GODEBUG: http2client=0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/seaweedfs/seaweedfs
      tag: ${{package.version}}
      expected-commit: e50d85c0f3697caf0ff9aca6662d59b4327a8424

  - uses: go/build
    with:
      packages: ./weed
      output: weed
      ldflags: |
        -s -w -extldflags -static -X github.com/seaweedfs/seaweedfs/weed/util.COMMIT=$(git rev-parse HEAD)

  - uses: strip

  - name: Add config file and entrypoint script
    runs: |
      mkdir -p ${{targets.destdir}}/etc/seaweedfs
      mkdir -p ${{targets.destdir}}/usr/bin
      cp ./docker/filer.toml ${{targets.destdir}}/etc/seaweedfs/filer.toml
      cp ./docker/entrypoint.sh ${{targets.destdir}}/usr/bin/entrypoint.sh
      chmod +x ${{targets.destdir}}/usr/bin/entrypoint.sh

test:
  pipeline:
    - name: "version command"
      runs: weed version

update:
  enabled: true
  github:
    identifier: seaweedfs/seaweedfs
