package:
  name: spicedb
  version: 1.35.2
  epoch: 0
  description: Open Source, Google Zanzibar-inspired fine-grained permissions database
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/authzed/spicedb
      tag: v${{package.version}}
      expected-commit: 8bcfb321e6ae2df55551d1cd7f0babc637a07597

  - uses: go/build
    with:
      packages: ./cmd/spicedb
      output: spicedb
      ldflags: -s -w -X github.com/jzelinskie/cobrautil/v2.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: authzed/spicedb
    strip-prefix: v
    use-tag: true
