package:
  name: tiff
  version: 4.6.0 # Remove CVE patches at the next release
  epoch: 4
  description: Provides support for the Tag Image File Format or TIFF
  copyright:
    - license: libtiff

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libjpeg-turbo-dev
      - libtool
      - libwebp-dev
      - python3
      - samurai
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8b20804fc0ddeaa93667b799b5e1a2a7dc9e3fb2
      repository: https://gitlab.com/libtiff/libtiff.git
      tag: v${{package.version}}

  - uses: patch
    with:
      # Source CVE-2023-6277: https://gitlab.com/libtiff/libtiff/-/merge_requests/545
      # Source CVE-2023-6228: https://gitlab.com/libtiff/libtiff/-/merge_requests/533
      patches: CVE-2023-6277.patch CVE-2023-6228.patch

  - runs: autoreconf -fiv

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: tiff-doc
    pipeline:
      - uses: split/manpages
    description: tiff manpages

  - name: tiff-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - tiff
        - zlib-dev
        - libjpeg-turbo-dev
        - libwebp-dev
        - zstd-dev
    description: tiff dev

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-prefix: v
