package:
  name: vertical-pod-autoscaler
  version: 1.2.0
  epoch: 1
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: vertical-pod-autoscaler-${{package.version}}
      expected-commit: 48e5e8f5eb8ed3ab1bc5b66f1f52234abcb15559

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0
      modroot: vertical-pod-autoscaler

  - uses: go/build
    with:
      modroot: vertical-pod-autoscaler
      packages: ./pkg/admission-controller
      output: admission-controller

subpackages:
  - name: vertical-pod-autoscaler-updater
    pipeline:
      - uses: go/build
        with:
          modroot: vertical-pod-autoscaler
          packages: ./pkg/updater
          output: updater

  - name: vertical-pod-autoscaler-recommender
    pipeline:
      - uses: go/build
        with:
          modroot: vertical-pod-autoscaler
          packages: ./pkg/recommender
          output: recommender
          vendor: "true"

update:
  enabled: true
  github:
    identifier: kubernetes/autoscaler
    strip-prefix: vertical-pod-autoscaler-
    use-tag: true
    tag-filter: vertical-pod-autoscaler-

test:
  environment:
    contents:
      packages:
        - vertical-pod-autoscaler-updater
        - vertical-pod-autoscaler-recommender
  pipeline:
    - runs: |
        for component in admission-controller updater recommender; do
          $component -h 2>&1 | grep -q "Usage of $component"
          $component 2>&1 | grep -q "unable to load in-cluster configuration"
        done
